linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - misspell
    - goconst
    - revive
    - errcheck
    - unconvert
    - staticcheck
    - unused
    - stylecheck
    - gosimple
    - goimports

issues:
  exclude:
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "Potential file inclusion via variable"
    - "should have( a package)? comment"
    - "Error return value of `logging.SetLogLevel` is not checked"
    - " type name will be used as .* by other packages,"
    - "(func|method) \\w+ should be \\w+"
    - "(type|var|struct field|(method|func) parameter) `\\w+` should be `\\w+`"
    - "(ST1003|G306|G301|G307|G108|G302|G204|G104)"
    - "don't use ALL_CAPS in Go names"
    - "string .* has .* occurrences, make it a constant"
    - "a blank import should be only in a main or test package, or have a comment justifying it"
    - "package comment should be of the form"
    - "should be of the form"
    - "var-naming"

  exclude-rules:
    - path: pkg/constants
      linters:
        - errcheck
    - path: pkg/specactors
      linters:
        - errcheck
  exclude-use-default: false

linters-settings:
  goconst:
    min-occurrences: 6

run:
  skip-dirs-use-default: false
  skip-files:
  - testhelper.go
  - ".*_gen\\.go$" # skip auto generated go files
